# Generated by Django 4.1.7 on 2023-03-02 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legajos', '0002_alter_empleado_options_alter_empleado_fechaingreso_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dni', models.IntegerField(default=0)),
                ('apellido', models.CharField(max_length=60)),
                ('nombre', models.CharField(max_length=60)),
                ('fechaNacimiento', models.DateField()),
                ('vinculo', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='empleado',
            name='area',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='empleado',
            name='categoria',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='empleado',
            name='lugarDeTrabajo',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='empleado',
            name='regimen',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='empleado',
            name='sector',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.CreateModel(
            name='Novedades',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tipoNovedad', models.CharField(choices=[('Cert', 'Cert'), ('Vacaciones', 'Vacaciones'), ('Licencia', 'Licencia'), ('Otro', 'Otro')], max_length=30)),
                ('descripcion', models.TextField()),
                ('tipodeacto', models.CharField(max_length=100)),
                ('numero', models.IntegerField()),
                ('adjunto', models.FileField(upload_to='')),
                ('empleadoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legajos.empleado')),
            ],
        ),
    ]
